accounts/urls.py
from django.urls import path
from .views import *

app_name = "accounts"

urlpatterns = [

    path("login/", login_view, name="login"),
    path("register/", register_view, name="register"),
    path("logout/", logout_view, name="logout"),

]

blog/urls.py
from django.conf import settings
from django.urls import path, include, re_path
from django.contrib import admin
from django.views.static import serve
from home.views import home_view
#from django.conf.urls.static import static
#from django.conf import settings
from prometheus_client import exposition
from post.metrics import REGISTRY
from django_prometheus import exports

urlpatterns = [

    path( '', home_view, name='home'),
    
    #path('', include('django_prometheus.urls')),

    path('metrics/', exports.ExportToDjangoView, name='metrics'),

    path("post/", include("post.urls")),
    
    path("accounts/", include("accounts.urls")),

    path("admin/", admin.site.urls),

]

urlpatterns += [
        path(
            "media/<path>",
            serve,
            {
                "document_root": settings.MEDIA_ROOT,
            },
        ),
        path(
            "static/<path>",
            serve,
            {
                "document_root": settings.STATIC_ROOT,
            },
        ),
    ]

post/urls.py
from django.urls import path
from .views import *

app_name = "post"

urlpatterns = [

    path("index/", post_index, name="index"),
    path("<int:id>/", post_detail, name='detail'),
    path("create/", post_create, name='create'),
    path("<int:id>/update/", post_update, name="update"),
    path("<int:id>/delete/", post_delete, name='delete'),
    path("<int:id>/predict/", post_predict, name='predict'),
    
]

home/views.py
from django.shortcuts import render, HttpResponse

def home_view(request):
    return render(request, 'home.html')

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}MLOPS{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    {% include 'messages.html' %}

    {% include "header.html" %}

    {% block body %}

    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function() {
            $('.navbar-toggle').collapse();
        });
    </script>
</body>
</html>

templates/header.html
<!-- Navbar Start -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="banner">
    <div class="container">

        <div class="navbar-header">

            <!-- Telefon ekranları için menü butonu -->
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- İsim Soyisim veya Marka İsmi -->
            <a href="{% url 'home' %}" class="navbar-brand">MLOPS</a>
        </div>
        
        <nav class="collapse navbar-collapse" id="navbar-collapse" role="navigation">

            <!-- Temel Sayfalar -->
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'post:create' %}" >Create</a></li>
                {% endif %}
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'post:index' %}">Index</a></li>
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'accounts:register' %}">Sign Up</a></li>
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
</nav>

<!-- Add the following script tags at the bottom of your HTML file, just before the closing </body> tag -->

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<script>
$(document).ready(function() {
  $('.navbar-toggle').collapse();
});
</script>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Home - {{ block.super }}
{% endblock %}

{% block body %}

<!doctype html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <title>MLOPS</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <style>
        #logo{
            position: relative;
        }

        * {
            max-width: 100%;
        }
        .fab {
            padding: 8px;
            font-size: 30px;
            width: 32px;
            text-align: center;
            text-decoration: none;
            margin: 5px 2px;
        }
        .fa-linkedin {
            background: #007bb5;
            color: white;
        }

        .fa-github{
            background: black;
            color: white;
        }
        .icon-text{
            width: 125px;
            font-size: 16px;
        }
        
        .icon-text span{
            margin:4px;
        }

        .class-one{
            position: relative;
            width: 200px;
            height: 200px;
            background-color: #007bb5;
            text-align: center; 
        }

        .class-right{
            position: relative;
            width: 200px;
            height: 200px;
            
        }

        .class-left{
            right: 0;
            left: 200px;
            margin: 50px;
        }

        .class-text{
            position: relative;
            padding-top: 4%;
            text-align: center;
            width: 200px;
            height: 200px;
        
        }

        .class-image{
            position: relative;
            width: 200px;
            height: 200px;

        }

        .class-deneme{
            left: 200px;
            margin: 50px;
        }

        .center {
            position: relative;
            text-align: center;
            margin-top: 25px;
            margin-left: auto;
            margin-right: auto;
        }

        .class-qr{
            position: relative;
            text-align: center;
        }
 
    </style>
</head>

<body>
<div container>
    <div class="row">
        <div class="col-md-4 col-sm-2 col-xs-2"></div>
        <div class="col-md-4 col-sm-8 col-xs-8" style="margin-top: auto; text-align:center;">
            <h1><p style="text-align: center">Machine Learning Operation</p></h1>
        </div>
    </div>
</div>

<div container>
    <div class="row">
        <div class="col-md-2 col-sm-1 col-xs-1"></div>
        <div class="col-md-8 col-sm-10 col-xs-10" style="margin-top: auto; text-align:center;">
            <p><img id="logo" src="{% static 'images/logo.png' %}" alt="MLOPS logo"/></p>
        </div>
    </div>
</div>

<div container-fluit>
    <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-6" style="margin-top: auto; text-align:center;">
            <img src="{% static 'images/muhsin.png' %}" width="200" height="200" alt="Ege Kutlu"/>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-6" style="margin-top: auto; text-align:center;">
            <div class="center">
                <p>
                    Muhsin Esad Torun
                </p>
                <p>
                    200722131
                </p>
                <p>
                    <a href="https://www.linkedin.com/in/muhsin-esad-torun-952655182/" class="icon-text fab fa-linkedin"><span> | </span> Linkedin </a>
                </p>
                <p>
                    <a href="https://github.com/muhsinesadtorun" class="icon-text fab fa-github"><span> | </span> Github </a> 
                </p>
            </div>
        </div>
    </div>
</div>

<div container-fluit>
    <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-6" style="margin-top: auto; text-align:center;">
            <div class="center">
                <p>
                    Ege Kutlu
                </p>
                <p>
                    180722007
                </p>
                <p>
                    <a href="https://www.linkedin.com/in/kutluege/" class="icon-text fab fa-linkedin"><span> | </span> Linkedin </a> 
                </p>
                <p>
                    <a href="https://github.com/kutluege" class="icon-text fab fa-github"><span> | </span> Github </a> 
                </p>
            </div>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-6" style="margin-top: auto; text-align:center;">
            <img src="{% static 'images/ege.png' %}" width="200" height="200" alt="Ege Kutlu"/>
        </div>
    </div>
</div>

<div container-fluit>
    <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-6" style="margin-top: auto; text-align:center;">
            <img src="{% static 'images/hasan.png' %}" width="200" height="200" alt="Ege Kutlu"/>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-6" style="margin-top: auto; text-align:center;">
            <div class="center">
                <p>
                    Hasan Evin
                </p>
                <p>
                    180722027
                </p>
                <p>
                    <a href="https://www.linkedin.com/in/hasanevin/" class="icon-text fab fa-linkedin"><span> | </span> Linkedin </a> 
                </p>
                <p>
                    <a href="https://github.com/hasanevinn" class="icon-text fab fa-github"><span> | </span> Github </a> 
                </p>
            </div>
        </div>
    </div>
</div>

<div container>
    <div class="row">
        <div class="col-md-5 col-sm-4 col-xs-4"></div>
        <div class="col-md-4 col-sm-6 col-xs-6">
            <p><img src="{% static 'images/qr.png' %}" width="250" height="250" alt="QR Code"/></p>
        </div>
    </div>
</div>

</body>
</html>

{% endblock %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          {{ message }}
        </div>
    {% endfor %}
{% endif %}